.PHONY: all
all:
	rm -rf distfiles
	mkdir -p distfiles/
	cp -r challenge distfiles/
	cp docker-compose.yml distfiles
	echo "fake{Thie is not a true flag. Please don't submit this, as you can see from I'm enclosing this by fake. The big brother is watching your submission, are you ok?}" > distfiles/challenge/public/flag.txt

