version: '3'
services:
  not_so_tiger:
    build:
      context: .
    working_dir: /home/pwn
    container_name: not_so_tiger
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9004:9999"
    entrypoint: /etc/init.sh
    restart: always
